# Site settings
title: AppBlocks.NET
author:
  name: Radical Dave
  email: dave@appblocks.net
description: "The best and easiest way to deploy Applications as a Service."

# Build settings
remote_theme: jekyll/architect
